language: php
sudo: false
php:
  - 5.4

before_script:
  - composer self-update -q
  - composer install
  - composer update -n

cache:
  directories:
  - vendor

script:
  - composer ci

after_success:
  - if [ $TRAVIS_BRANCH = 'master' ]; then sh generate_doc.sh; fi

